### PR TITLE
Remove PieMapping from "Used and Supported by"

### PR DESCRIPTION
**Pull request by slavomirvojacek**
As this is no longer true.

### CODE REVIEW

**Comment by philpl** [comment]
@slavomirvojacek Congrats on the apparent refactor 💪 Hope you guys are having fun! 😃 :tada:

**Comment by rgbkrk** [comment]
What are you all using now?

**Comment by philpl** [comment]
@rgbkrk I'd guess they've fully switched to Redux?

**Comment by slavomirvojacek** [comment]
We are slowly porting sections of the app onto a new architecture, so developers from various backgrounds can contribute to the codebase.

More specifically, we use:

- **TypeScript**, because we believe that code quality is important and that type annotations are in fact useful
- **Redux**, because we believe that one should use a industry-standard, thoroughly tested, and exceptionally documented solution to take care of as important a part of one's codebase as its state-management
- **Unit Testing** (perhaps the most controversially), because we believe that any code that is NOT tested is legacy code

Hope this answers all your questions.

**Comment by philpl** [comment]
@slavomirvojacek Sounds good!

I'm wondering if you've started using redux-observable, to get some side effect abstraction going in Redux? Or are you sticking to wrapping some observables in thunks?

I know that I'm certainly a big fan of Redux Observable, and I know that @rgbkrk is one as well 😄

**Comment by slavomirvojacek** [comment]
I am sad to inform you that we have decided to only use libraries and frameworks that we actually need to deliver a working solution for our clients.

Hope this answers your question.

**Comment by rgbkrk** [comment]
Thanks for the response, sounds like it was a terrific choice for you all.

**Pull request merged**
